name: Building Docker container
on:
  push:
    branches:
      - master
      - develop
      - docker_build_workflow
  pull_request:
    branches:
      - master
      - develop
    tags:
      - v*

jobs:
  build_docker:
    runs-on: ubuntu-latest
    name: Running pylint checks
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
        id: fetch-source
      - name: Build docker image
        run: docker build -t test ./
