name: Building Docker container
on:
  push:
    branches:
      - master
      - develop
      - docker_build_workflow
  pull_request:
    branches:
      - master
      - develop
    tags:
      - v*

jobs:
  build_docker:
    runs-on: ubuntu-latest
    name: Build docker container
    strategy:
      matrix:
          app: [betydb2geojson, shp2geojson]
          include:
            - app: betydb2geojson
              parameters: https://terraref.ncsa.illinois.edu/bety /mnt/bety_plots.geojson
              test_results: if [[ -f "bety_plots.geojson" ]]; then echo "Test betydb2geojson success"; exit 0; else echo "App failed - betydb2geojson"; exit 1; fi;
            - app: shp2geojson
              parameters: /mnt/plot_shapes.shp /mnt/shp_plots.geojson
              test_results: if [[ -f "shp_plots.geojson" ]]; then echo "Test shp2geojson success"; exit 0; else echo "App failed - shp2geojson"; exit 1; fi;
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
        id: fetch-source
      - name: Build docker image
        run: docker build -t test ./
      - name: Shp2geojson download check
        if: ${{ matrix.app  == 'shp2geojson' }}
        run: curl -X GET https://de.cyverse.org/dl/d/3C8A23C0-F77A-4598-ADC4-874EB265F9B0/scif_test_data.tar.gz > scif_test_data.tar.gz &&
             tar xvzf scif_test_data.tar.gz -C "./" &&
             ls -l
      - name: Run test
        run: docker run --rm -v `pwd`:/mnt test:latest run ${{ matrix.app }} ${{ matrix.parameters }}
      - name: Folder listing
        run: ls -l
      - name: Check results
        run: ${{ matrix.test_results }}
