name: Building Docker container
on:
  push:
    branches:
      - master
      - develop
      - docker_build_workflow
  pull_request:
    branches:
      - master
      - develop
    tags:
      - v*

jobs:
  build_docker:
    runs-on: ubuntu-latest
    name: Build docker container
    strategy:
      matrix:
          app: [betydb2geojson]
          include:
            - app: betydb2geojson
              parameters: https://terraref.ncsa.illinois.edu/bety bety_plots.geojson
              test_results: if [[ -f "bety_plots.geojson" ]]; then echo "Test success"; exit 0; else echo "App failed"; exit 1; fi;
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
        id: fetch-source
      - name: Build docker image
        run: docker build -t test ./
      - name: Run test
        run: docker run --rm -v `pwd`:/mnt test:latest run ${{ matrix.app }} ${{ matrix.parameters }}
      - name: Check results
        run: ${{ matrix.test_results }}
