name: Building Docker container
on:
  push:
    branches:
      - master
      - develop
      - docker_build_workflow
  pull_request:
    branches:
      - master
      - develop
    tags:
      - v*

jobs:
  build_docker:
    runs-on: ubuntu-latest
    name: Build docker container
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
        id: fetch-source
      - name: Build docker image
        run: docker build -t scif_test:latest ./
      - name: Compress docker image
        run: docker save scif_test:latest | gzip -7 -c - > scif_test_image.tar.gz
      - name: Upload docker image
        uses: actions/upload-artifact@v2
        with:
          name: scif_test_image
          path: scif_test_image.tar.gz

  app_testing:
    runs-on: ubuntu-latest
    needs: build_docker
    name: Test simple apps (not workflow apps)
    strategy:
      matrix:
          app: [betydb2geojson, shp2geojson]
          include:
            - app: betydb2geojson
              parameters: https://terraref.ncsa.illinois.edu/bety /mnt/bety_plots.geojson
              test_results: if [[ -f "bety_plots.geojson" ]]; then echo "Test betydb2geojson success"; exit 0; else echo "App failed - betydb2geojson"; exit 1; fi;
            - app: shp2geojson
              parameters: /mnt/plot_shapes.shp /mnt/shp_plots.geojson
              test_results: if [[ -f "shp_plots.geojson" ]]; then echo "Test shp2geojson success"; exit 0; else echo "App failed - shp2geojson"; exit 1; fi;
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v2
        with:
          name: scif_test_image
          path: ./
      - name: Load docker image
        run: |
             ls -l
             gunzip scif_test_image.tar.gz
             docker load --input scif_test_image.tar
             docker images
      - name: Shp2geojson download check
        if: ${{ matrix.app  == 'shp2geojson' }}
        run: |
             curl -X GET https://de.cyverse.org/dl/d/3C8A23C0-F77A-4598-ADC4-874EB265F9B0/scif_test_data.tar.gz > scif_test_data.tar.gz
             tar xvzf scif_test_data.tar.gz -C "./"
             ls -l
      - name: Run test
        run: docker run --rm -v `pwd`:/mnt scif_test:latest run ${{ matrix.app }} ${{ matrix.parameters }}
      - name: Folder listing
        run: ls -l
      - name: Check results
        run: ${{ matrix.test_results }}

  workflow_testing:
    runs-on: ubuntu-latest
    needs: build_docker
    name: Testing workflows
    strategy:
      matrix:
          app: [short_workflow]
          include:
            - app: short_workflow
              data_file_archive_url: "https://de.cyverse.org/dl/d/3C8A23C0-F77A-4598-ADC4-874EB265F9B0/scif_test_data.tar.gz"
              parameters: /mnt/orthomosaic.tif /mnt/plot_shapes.shp
              result_check_script: "short_workflow_check.sh"
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
        id: fetch-source
      - name: Prepare folders
        run: |
             mkdir ./inputs
             mkdir ./outputs
             mkdir ./checkpoints
      - name: Download docker image
        uses: actions/download-artifact@v2
        with:
          name: scif_test_image
          path: ./
      - name: Decompress and load docker image
        run: |
             ls -l
             gunzip scif_test_image.tar.gz
             docker load --input scif_test_image.tar
             docker images
      - name: Download testing data files
        run: |
             curl -X GET ${{ matrix.data_file_archive_url }} > test_data.tar.gz
             tar xvzf test_data.tar.gz -C "./inputs/"
             ls -l
             ls -l ./inputs/*
      - name: Run test
        run: docker run --rm -v "${PWD}/inputs:/scif/data/odm_workflow/images" -v "${PWD}/outputs:/output" -v "${PWD}/checkpoints:/scif/data/short_workflow" scif_test:latest run short_workflow orthomosaic plot_shapes.shp
      - name: Show outputs folder
        run: |
             ls -l ./outputs
             ls -l ./checkpoints
      - name: Check outputs
        run: |
             chmod +x "./.github/workflows/${{ matrix.result_check_script }}"
             "./.github/workflows/${{ matrix.result_check_script }}"
      - name: Check artifacts
        run: |
             WFL=$(find ./checkpoints | grep "makeflowlog" | wc -l| tr -d '[:space:]')
             echo $WFL
             if [[ "$WFL" == "2" ]]; then echo "The correct number of makeflow log files were found"; else "Makeflow log count error"; exit 2; fi

  artifact_cleanup:
    runs-on: ubuntu-latest
    needs: [app_testing, workflow_testing]
    name: Cleanup artifacts upon success
    steps:
      - name: Remove docker artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: scif_test_image
